### ISSUE TITLE
Preprocessing the darpa theia dataset misses data.pt file

### ISSUE THREAD

**Issue by fhschina** [timpostuvan/CTDG-link-anomaly-detection#1]
Hi,

I try to run your `TGB-link-anomaly-detection/tgb/datasets/darpa/preprocess_darpa_theia_trace.py` script but encounter an error indicating that the `data.pt` file is missing. This issue appears to stem from `line 17: self.INPUT_FILE = os.path.join(self.ROOT_FOLDER, "data.pt")`.

I am confused about the DARPA dataset. I download the DARPA Theia dataset, which is in .json format, but I do not see any .pt file. Is there an additional layer of preprocessing required before running the script?

Thanks!

**Comment by timpostuvan** [comment]
Hello,

you can get the DARPA-THEIA dataset [here](https://github.com/JakubReha/ProvCTDG/tree/master). To generate `data.pt` file, I think you need to take the pre-processed files from the repository and load them with PyTorch Geometric (probably [here](https://github.com/JakubReha/ProvCTDG/blob/master/src/datasets/darpa.py#L16)).
